// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmkhotxkrenclfsjbfqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impta2hvdHhrcmVuY2xmc2piZnFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3ODkzNjEsImV4cCI6MjA2NTM2NTM2MX0.Q3eBs-OtXNDNT7O4JurK8n7caKOenfEtTQiQBvmZcng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);